### ISSUE TITLE
Feedback/Errors on Getting Started Documentation

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#201]
This is a review of the [following document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS).

### Technical Errors: 

- [x]  yeoman generator generates a reference to a scss file that no longer exists in formation directory: `@import "~@department-of-veterans-affairs/formation/sass/modules/m-progress-bar";` Once I ran `yarn add` on this package, it was fixed.

- [x] basic schema can be imported from `'vets-json-schema/dist/definitions.json'` and not from `'vets-json-schema/dist/VIC-schema.json'`;
- [x] I was able to import the `fullName` schema and `fullNameUI` schema UI from 
```
import fullSchema from 'vets-json-schema/dist/definitions.json';
import fullNameUI from 'platform/forms-system/src/js/definitions/fullName'; // also here: platform\forms\definitions\fullName.js
``` 
instead of
```
import fullSchema from 'vets-json-schema/dist/VIC-schema.json';
import fullNameUI from '../../common/schemaform/definitions/fullName';
```
- [x] Import for `set` [as prescribed](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS#Modifying-common-definitions) is not working for me, but importing like so did work for me:
```
import set from 'platform/utilities/data/set';
```

### General Feedback/Questions:

- radio buttons: 
```
// a11y requirement: aria-describedby ID's *must* exist on the page;
// and we conditionally add content based on the selection
selectedProps: {
  Y: { 'aria-describedby': 'some_id' },
  N: { 'aria-describedby': 'different_id' }
}
```
`aria-describedby` is used multiple places, but there is no contextual information about what label or item this would point to, since the id is non existent. Is this a field that can be dynamically set? Typically label-for can indicate the text for a radio button. Curious what the history is behind this/ why this approach is being used.
- Curious why there are disclaimers that say "DISCLAIMER - TRY NOT TO USE THIS ANYMORE". Is it an accessibility issue?

**Comment by mlauren** [comment]
hi @taylorkaren here is the feedback I had for that introductory article. Let me know if there are any ways to improve. Some of these questions may be for @micahchiang

**Comment by mlauren** [comment]
@sdk-irl  I was curious about `aria-describedby` as used in this document. Do you know what element this `aria-describedby` is supposed to point to? 
![Screen Shot 2022-04-04 at 4.05.23 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/e941eb38-ace1-45d3-b96f-78c282d0dd4c)![Screen Shot 2022-04-04 at 4.05.17 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/c6cf835c-863d-4bdb-a980-3dc95b88a9bd)

**Comment by sdk-irl** [comment]
I wasn't aware that there was an ally req to have aria-describedby on a radio group--I'm not sure if it's because of the radio group, or because it's generated by the form config. It seems like it was directly copied from a code example, but I can't find it in vets-website anywhere. 

@bjmccotter7192 did you pull this directly from vets-website or was this from the original getting strarted page?

**Comment by bjmccotter7192** [comment]
@sdk-irl I believe the examples on that page were from the original documentation here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/form-tutorial-intermediate

**Comment by taylorkaren** [comment]
@mlauren: I can answer the Disclaimer question. This is because conditionally showing and hiding information is a pattern that platform is trying to move away from for accessibility reasons. I don't have any additional details on this; I took that information from a comment Micah made on this page, he may be able to provide additional insight.

As for the aria-describedby question, I don't think there is a specific ID it is meant to point to. It's basically dummy text to show what the concept is.

Do you need anything else to complete work on this ticket and move it to a Ready for Review status?

**Comment by mlauren** [comment]
@taylorkaren no I think all of my questions have been answered. I will move to ready for review.

**Comment by taylorkaren** [comment]
These updates are in Production (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---Getting-Started-with-the-Forms-Library.2104197265.html) as of 4/7/22.
