### ISSUE TITLE
(Placeholder) Telephone Field

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#204]
Should have the same look as already established on design.va.gov and Storybook. Work is to wrap the radio group in the Formik wrapper, not change anything with the look and feel.

**Comment by micahchiang** [comment]
Choosing to close this ticket because:
- The va-telephone web component on storybook is actually only a read only component, not a form input
- At their most basic form, telephone fields are just text inputs. We already have a va-forms-system-core TextField. Validation for correct phone number patterns should follow a similar convention [as this one does](https://github.com/department-of-veterans-affairs/vets-website/blob/5e67f81bafc4bb014f1d7259dabf9045e536121d/src/applications/check-in/components/pages/Edit/Email.jsx#L80) which uses the existing text input web component. 

Related, vets-website has form validations that are imported from the platform directory [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/5e67f81bafc4bb014f1d7259dabf9045e536121d/src/applications/check-in/components/pages/Edit/Email.jsx#L8). We may want to consider moving the validations library to va-forms-system-core.
