### ISSUE TITLE
(Needs AC/see comments from Matt) Review Page Pattern Styles --> VAFSC

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#561]
## Task Description
- Per discussion in the 8/19/22 standup call, take the Review Page styles currently on vets-website and embed them in the VAFSC code so they are less exposed.
    - Locate the style sheet in the form builder directory or in the style directory in the package.
- Review the comments on this ticket that capture feedback from Matt and write post-transition tickets to capture any thoughts we have on how that feedback might be addressed. 

## Context
- Styles are currently included [here](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/main/examples/form-styles.css).
- This was first brought up in the thread [here](https://dsva.slack.com/archives/C02L9109NMQ/p1660688331603329?thread_ts=1660688218.761489&cid=C02L9109NMQ).

## Acceptance Criteria
**_ADD_**

**Comment by taylorkaren** [comment]
Thoughts from Matt (from [this Slack thread](https://dsva.slack.com/archives/C02L9109NMQ/p1661176376570159?thread_ts=1660688218.761489&cid=C02L9109NMQ)):
- By default VFS Teams should get a template for a Review page that delivers a consistent layout.
- My belief is that if they need to deviate in a significant way they should go through CollabCycle which requires that they propose and validate any design deviation.
- Teams should have the flexibility to make insignificant or minor changes that don't change the design intents of the page.
- The challenge is figuring out where that line is which is why I think CollabCycle is helpful here to govern deviations. "Significant" is obviously open to interpretation so our documentation might help to clarify what significant, and insignificant, deviations might be. Having the history of the current system is useful here and should help us draw the distinction.
- Additional templates to the default can be added to the Forms System to manage known and accepted deviations to the layout/presentation.
- If those templates would be easier to maintain by having sections of the Review page delivered via composed or molecule level (to borrow from Brad Frost's Atomic Design lexicon; essentially components that may include other components) components then great. I'd like us to head in that direction in the Design System overall. We should get the atoms (buttons, form elements, etc.) from USWDS (for the most part and only once they can provide web-components) and build the molecules that are specific and appropriate for the VA ourselves. The components needed for a Review page layout are a good example. Those are not coming from USWDS any time soon and we have the design and research to back-up our decisions.

**Comment by taylorkaren** [comment]
Further thoughts from Matt in the 8/23/22 PO Sync call:
- Forms Library Team should set a course and follow that - put the styles in the VAFSC and leave it at that for now. 
- Things to think about for later (put these in placeholder tickets if we have ideas for implementation:
    - Provide a Review Page template for teams, OK if there is some configuration available in the template.
    - Teams should not need to deviate dramatically from what is provided in the template. 
    - Let people come to Collab Cycle with the use case to deviate from what is provided, and if the use case merits a deviation, design to that use case rather than trying to provide out of the box "flexibility." 
    - What is the right component here? Once we get to V3 on the US WDS, we can focus more on these kind of composed components and make patterns easier to implement by pulling those parts “off the shelf.”
